/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IdentityRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "investorCountry"
      | "isVerified"
      | "kycAgents"
      | "owner"
      | "registerInvestor"
      | "removeInvestor"
      | "renounceOwnership"
      | "setKYCAgent"
      | "transferOwnership"
      | "updateInvestor"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "InvestorRegistered"
      | "InvestorRemoved"
      | "InvestorUpdated"
      | "KYCAgentSet"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "investorCountry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "kycAgents",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerInvestor",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeInvestor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setKYCAgent",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateInvestor",
    values: [AddressLike, boolean, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "investorCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "kycAgents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerInvestor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeInvestor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setKYCAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateInvestor",
    data: BytesLike
  ): Result;
}

export namespace InvestorRegisteredEvent {
  export type InputTuple = [wallet: AddressLike, country: BigNumberish];
  export type OutputTuple = [wallet: string, country: bigint];
  export interface OutputObject {
    wallet: string;
    country: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestorRemovedEvent {
  export type InputTuple = [wallet: AddressLike];
  export type OutputTuple = [wallet: string];
  export interface OutputObject {
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestorUpdatedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    verified: boolean,
    country: BigNumberish
  ];
  export type OutputTuple = [
    wallet: string,
    verified: boolean,
    country: bigint
  ];
  export interface OutputObject {
    wallet: string;
    verified: boolean;
    country: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KYCAgentSetEvent {
  export type InputTuple = [agent: AddressLike, allowed: boolean];
  export type OutputTuple = [agent: string, allowed: boolean];
  export interface OutputObject {
    agent: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IdentityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IdentityRegistry;
  waitForDeployment(): Promise<this>;

  interface: IdentityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  investorCountry: TypedContractMethod<
    [investor: AddressLike],
    [bigint],
    "view"
  >;

  isVerified: TypedContractMethod<[investor: AddressLike], [boolean], "view">;

  kycAgents: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerInvestor: TypedContractMethod<
    [wallet: AddressLike, country: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeInvestor: TypedContractMethod<
    [wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setKYCAgent: TypedContractMethod<
    [agent: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateInvestor: TypedContractMethod<
    [wallet: AddressLike, verified: boolean, country: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "investorCountry"
  ): TypedContractMethod<[investor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<[investor: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "kycAgents"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerInvestor"
  ): TypedContractMethod<
    [wallet: AddressLike, country: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeInvestor"
  ): TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setKYCAgent"
  ): TypedContractMethod<
    [agent: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateInvestor"
  ): TypedContractMethod<
    [wallet: AddressLike, verified: boolean, country: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "InvestorRegistered"
  ): TypedContractEvent<
    InvestorRegisteredEvent.InputTuple,
    InvestorRegisteredEvent.OutputTuple,
    InvestorRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "InvestorRemoved"
  ): TypedContractEvent<
    InvestorRemovedEvent.InputTuple,
    InvestorRemovedEvent.OutputTuple,
    InvestorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "InvestorUpdated"
  ): TypedContractEvent<
    InvestorUpdatedEvent.InputTuple,
    InvestorUpdatedEvent.OutputTuple,
    InvestorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "KYCAgentSet"
  ): TypedContractEvent<
    KYCAgentSetEvent.InputTuple,
    KYCAgentSetEvent.OutputTuple,
    KYCAgentSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "InvestorRegistered(address,uint16)": TypedContractEvent<
      InvestorRegisteredEvent.InputTuple,
      InvestorRegisteredEvent.OutputTuple,
      InvestorRegisteredEvent.OutputObject
    >;
    InvestorRegistered: TypedContractEvent<
      InvestorRegisteredEvent.InputTuple,
      InvestorRegisteredEvent.OutputTuple,
      InvestorRegisteredEvent.OutputObject
    >;

    "InvestorRemoved(address)": TypedContractEvent<
      InvestorRemovedEvent.InputTuple,
      InvestorRemovedEvent.OutputTuple,
      InvestorRemovedEvent.OutputObject
    >;
    InvestorRemoved: TypedContractEvent<
      InvestorRemovedEvent.InputTuple,
      InvestorRemovedEvent.OutputTuple,
      InvestorRemovedEvent.OutputObject
    >;

    "InvestorUpdated(address,bool,uint16)": TypedContractEvent<
      InvestorUpdatedEvent.InputTuple,
      InvestorUpdatedEvent.OutputTuple,
      InvestorUpdatedEvent.OutputObject
    >;
    InvestorUpdated: TypedContractEvent<
      InvestorUpdatedEvent.InputTuple,
      InvestorUpdatedEvent.OutputTuple,
      InvestorUpdatedEvent.OutputObject
    >;

    "KYCAgentSet(address,bool)": TypedContractEvent<
      KYCAgentSetEvent.InputTuple,
      KYCAgentSetEvent.OutputTuple,
      KYCAgentSetEvent.OutputObject
    >;
    KYCAgentSet: TypedContractEvent<
      KYCAgentSetEvent.InputTuple,
      KYCAgentSetEvent.OutputTuple,
      KYCAgentSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
