/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface NAVOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "chainlinkFeed"
      | "latestNAV"
      | "manualDecimals"
      | "manualNav"
      | "manualUpdatedAt"
      | "owner"
      | "renounceOwnership"
      | "setChainlinkFeed"
      | "setManualNAV"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "NAVUpdated" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "chainlinkFeed",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "latestNAV", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "manualDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "manualNav", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "manualUpdatedAt",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setChainlinkFeed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setManualNAV",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "chainlinkFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "latestNAV", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "manualDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "manualNav", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "manualUpdatedAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setChainlinkFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setManualNAV",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace NAVUpdatedEvent {
  export type InputTuple = [
    nav: BigNumberish,
    decimals: BigNumberish,
    fromChainlink: boolean
  ];
  export type OutputTuple = [
    nav: bigint,
    decimals: bigint,
    fromChainlink: boolean
  ];
  export interface OutputObject {
    nav: bigint;
    decimals: bigint;
    fromChainlink: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NAVOracle extends BaseContract {
  connect(runner?: ContractRunner | null): NAVOracle;
  waitForDeployment(): Promise<this>;

  interface: NAVOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  chainlinkFeed: TypedContractMethod<[], [string], "view">;

  latestNAV: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean] & {
        nav: bigint;
        decimals_: bigint;
        updatedAt: bigint;
        chainlink: boolean;
      }
    ],
    "view"
  >;

  manualDecimals: TypedContractMethod<[], [bigint], "view">;

  manualNav: TypedContractMethod<[], [bigint], "view">;

  manualUpdatedAt: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setChainlinkFeed: TypedContractMethod<
    [feed: AddressLike],
    [void],
    "nonpayable"
  >;

  setManualNAV: TypedContractMethod<
    [nav_: BigNumberish, decimals_: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "chainlinkFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "latestNAV"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean] & {
        nav: bigint;
        decimals_: bigint;
        updatedAt: bigint;
        chainlink: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "manualDecimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "manualNav"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "manualUpdatedAt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setChainlinkFeed"
  ): TypedContractMethod<[feed: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setManualNAV"
  ): TypedContractMethod<
    [nav_: BigNumberish, decimals_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "NAVUpdated"
  ): TypedContractEvent<
    NAVUpdatedEvent.InputTuple,
    NAVUpdatedEvent.OutputTuple,
    NAVUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "NAVUpdated(uint256,uint8,bool)": TypedContractEvent<
      NAVUpdatedEvent.InputTuple,
      NAVUpdatedEvent.OutputTuple,
      NAVUpdatedEvent.OutputObject
    >;
    NAVUpdated: TypedContractEvent<
      NAVUpdatedEvent.InputTuple,
      NAVUpdatedEvent.OutputTuple,
      NAVUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
