/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  INAVOracle,
  INAVOracleInterface,
} from "../../../../contracts/lending/interfaces/INAVOracle";

const _abi = [
  {
    inputs: [],
    name: "latestNAV",
    outputs: [
      {
        internalType: "uint256",
        name: "nav",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "decimals_",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "updatedAt",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "chainlink",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class INAVOracle__factory {
  static readonly abi = _abi;
  static createInterface(): INAVOracleInterface {
    return new Interface(_abi) as INAVOracleInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): INAVOracle {
    return new Contract(address, _abi, runner) as unknown as INAVOracle;
  }
}
