/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IIdentityRegistry,
  IIdentityRegistryInterface,
} from "../../contracts/IIdentityRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "investor",
        type: "address",
      },
    ],
    name: "investorCountry",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "investor",
        type: "address",
      },
    ],
    name: "isVerified",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IIdentityRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IIdentityRegistryInterface {
    return new Interface(_abi) as IIdentityRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IIdentityRegistry {
    return new Contract(address, _abi, runner) as unknown as IIdentityRegistry;
  }
}
