/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PurDexOracleRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ethUsdFeed"
      | "ethUsdPrice"
      | "initialize"
      | "manualEthUsdPrice1e18"
      | "manualPurUsdPrice1e18"
      | "maxAge"
      | "owner"
      | "proxiableUUID"
      | "purUsdOracle"
      | "purUsdPrice"
      | "renounceOwnership"
      | "setEthUsdFeed"
      | "setManualEthUsdPrice"
      | "setManualPurUsdPrice"
      | "setMaxAge"
      | "setPurUsdOracle"
      | "transferOwnership"
      | "upgradeTo"
      | "upgradeToAndCall"
      | "useManualEth"
      | "useManualPur"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminChanged"
      | "BeaconUpgraded"
      | "EthFeedUpdated"
      | "Initialized"
      | "ManualEthUpdated"
      | "ManualPurUpdated"
      | "MaxAgeUpdated"
      | "OwnershipTransferred"
      | "PurOracleUpdated"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ethUsdFeed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ethUsdPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "manualEthUsdPrice1e18",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "manualPurUsdPrice1e18",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "maxAge", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purUsdOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purUsdPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setEthUsdFeed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setManualEthUsdPrice",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setManualPurUsdPrice",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxAge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPurUsdOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "useManualEth",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "useManualPur",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "ethUsdFeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ethUsdPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "manualEthUsdPrice1e18",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "manualPurUsdPrice1e18",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "maxAge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purUsdOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purUsdPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEthUsdFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setManualEthUsdPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setManualPurUsdPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setMaxAge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPurUsdOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "useManualEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "useManualPur",
    data: BytesLike
  ): Result;
}

export namespace AdminChangedEvent {
  export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [previousAdmin: string, newAdmin: string];
  export interface OutputObject {
    previousAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeaconUpgradedEvent {
  export type InputTuple = [beacon: AddressLike];
  export type OutputTuple = [beacon: string];
  export interface OutputObject {
    beacon: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EthFeedUpdatedEvent {
  export type InputTuple = [feed: AddressLike];
  export type OutputTuple = [feed: string];
  export interface OutputObject {
    feed: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManualEthUpdatedEvent {
  export type InputTuple = [price1e18: BigNumberish, enabled: boolean];
  export type OutputTuple = [price1e18: bigint, enabled: boolean];
  export interface OutputObject {
    price1e18: bigint;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManualPurUpdatedEvent {
  export type InputTuple = [price1e18: BigNumberish, enabled: boolean];
  export type OutputTuple = [price1e18: bigint, enabled: boolean];
  export interface OutputObject {
    price1e18: bigint;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxAgeUpdatedEvent {
  export type InputTuple = [maxAge: BigNumberish];
  export type OutputTuple = [maxAge: bigint];
  export interface OutputObject {
    maxAge: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PurOracleUpdatedEvent {
  export type InputTuple = [oracle: AddressLike];
  export type OutputTuple = [oracle: string];
  export interface OutputObject {
    oracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PurDexOracleRouter extends BaseContract {
  connect(runner?: ContractRunner | null): PurDexOracleRouter;
  waitForDeployment(): Promise<this>;

  interface: PurDexOracleRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ethUsdFeed: TypedContractMethod<[], [string], "view">;

  ethUsdPrice: TypedContractMethod<
    [],
    [[bigint, bigint] & { price1e18: bigint; updatedAt: bigint }],
    "view"
  >;

  initialize: TypedContractMethod<
    [_ethUsdFeed: AddressLike, _purUsdOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  manualEthUsdPrice1e18: TypedContractMethod<[], [bigint], "view">;

  manualPurUsdPrice1e18: TypedContractMethod<[], [bigint], "view">;

  maxAge: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  purUsdOracle: TypedContractMethod<[], [string], "view">;

  purUsdPrice: TypedContractMethod<
    [],
    [[bigint, bigint] & { price1e18: bigint; updatedAt: bigint }],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setEthUsdFeed: TypedContractMethod<[feed: AddressLike], [void], "nonpayable">;

  setManualEthUsdPrice: TypedContractMethod<
    [price1e18: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;

  setManualPurUsdPrice: TypedContractMethod<
    [price1e18: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;

  setMaxAge: TypedContractMethod<[_maxAge: BigNumberish], [void], "nonpayable">;

  setPurUsdOracle: TypedContractMethod<
    [oracle: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeTo: TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  useManualEth: TypedContractMethod<[], [boolean], "view">;

  useManualPur: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ethUsdFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ethUsdPrice"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { price1e18: bigint; updatedAt: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_ethUsdFeed: AddressLike, _purUsdOracle: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "manualEthUsdPrice1e18"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "manualPurUsdPrice1e18"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxAge"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purUsdOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purUsdPrice"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { price1e18: bigint; updatedAt: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEthUsdFeed"
  ): TypedContractMethod<[feed: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setManualEthUsdPrice"
  ): TypedContractMethod<
    [price1e18: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setManualPurUsdPrice"
  ): TypedContractMethod<
    [price1e18: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxAge"
  ): TypedContractMethod<[_maxAge: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPurUsdOracle"
  ): TypedContractMethod<[oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeTo"
  ): TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "useManualEth"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "useManualPur"
  ): TypedContractMethod<[], [boolean], "view">;

  getEvent(
    key: "AdminChanged"
  ): TypedContractEvent<
    AdminChangedEvent.InputTuple,
    AdminChangedEvent.OutputTuple,
    AdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "BeaconUpgraded"
  ): TypedContractEvent<
    BeaconUpgradedEvent.InputTuple,
    BeaconUpgradedEvent.OutputTuple,
    BeaconUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "EthFeedUpdated"
  ): TypedContractEvent<
    EthFeedUpdatedEvent.InputTuple,
    EthFeedUpdatedEvent.OutputTuple,
    EthFeedUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "ManualEthUpdated"
  ): TypedContractEvent<
    ManualEthUpdatedEvent.InputTuple,
    ManualEthUpdatedEvent.OutputTuple,
    ManualEthUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ManualPurUpdated"
  ): TypedContractEvent<
    ManualPurUpdatedEvent.InputTuple,
    ManualPurUpdatedEvent.OutputTuple,
    ManualPurUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MaxAgeUpdated"
  ): TypedContractEvent<
    MaxAgeUpdatedEvent.InputTuple,
    MaxAgeUpdatedEvent.OutputTuple,
    MaxAgeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PurOracleUpdated"
  ): TypedContractEvent<
    PurOracleUpdatedEvent.InputTuple,
    PurOracleUpdatedEvent.OutputTuple,
    PurOracleUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "AdminChanged(address,address)": TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;
    AdminChanged: TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;

    "BeaconUpgraded(address)": TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;
    BeaconUpgraded: TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;

    "EthFeedUpdated(address)": TypedContractEvent<
      EthFeedUpdatedEvent.InputTuple,
      EthFeedUpdatedEvent.OutputTuple,
      EthFeedUpdatedEvent.OutputObject
    >;
    EthFeedUpdated: TypedContractEvent<
      EthFeedUpdatedEvent.InputTuple,
      EthFeedUpdatedEvent.OutputTuple,
      EthFeedUpdatedEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "ManualEthUpdated(uint256,bool)": TypedContractEvent<
      ManualEthUpdatedEvent.InputTuple,
      ManualEthUpdatedEvent.OutputTuple,
      ManualEthUpdatedEvent.OutputObject
    >;
    ManualEthUpdated: TypedContractEvent<
      ManualEthUpdatedEvent.InputTuple,
      ManualEthUpdatedEvent.OutputTuple,
      ManualEthUpdatedEvent.OutputObject
    >;

    "ManualPurUpdated(uint256,bool)": TypedContractEvent<
      ManualPurUpdatedEvent.InputTuple,
      ManualPurUpdatedEvent.OutputTuple,
      ManualPurUpdatedEvent.OutputObject
    >;
    ManualPurUpdated: TypedContractEvent<
      ManualPurUpdatedEvent.InputTuple,
      ManualPurUpdatedEvent.OutputTuple,
      ManualPurUpdatedEvent.OutputObject
    >;

    "MaxAgeUpdated(uint256)": TypedContractEvent<
      MaxAgeUpdatedEvent.InputTuple,
      MaxAgeUpdatedEvent.OutputTuple,
      MaxAgeUpdatedEvent.OutputObject
    >;
    MaxAgeUpdated: TypedContractEvent<
      MaxAgeUpdatedEvent.InputTuple,
      MaxAgeUpdatedEvent.OutputTuple,
      MaxAgeUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PurOracleUpdated(address)": TypedContractEvent<
      PurOracleUpdatedEvent.InputTuple,
      PurOracleUpdatedEvent.OutputTuple,
      PurOracleUpdatedEvent.OutputObject
    >;
    PurOracleUpdated: TypedContractEvent<
      PurOracleUpdatedEvent.InputTuple,
      PurOracleUpdatedEvent.OutputTuple,
      PurOracleUpdatedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
