/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  PurDexLibrary,
  PurDexLibraryInterface,
} from "../../../../contracts/dex/libraries/PurDexLibrary";

const _abi = [
  {
    inputs: [],
    name: "PurDexLibrary__IdenticalAddresses",
    type: "error",
  },
  {
    inputs: [],
    name: "PurDexLibrary__InsufficientAmount",
    type: "error",
  },
  {
    inputs: [],
    name: "PurDexLibrary__InsufficientLiquidity",
    type: "error",
  },
  {
    inputs: [],
    name: "PurDexLibrary__ZeroAddress",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220d964a4e15fc71f3d43eabace02781709171e22058b8add527564253ad7d9d1af64736f6c63430008220033";

type PurDexLibraryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PurDexLibraryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PurDexLibrary__factory extends ContractFactory {
  constructor(...args: PurDexLibraryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      PurDexLibrary & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): PurDexLibrary__factory {
    return super.connect(runner) as PurDexLibrary__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PurDexLibraryInterface {
    return new Interface(_abi) as PurDexLibraryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): PurDexLibrary {
    return new Contract(address, _abi, runner) as unknown as PurDexLibrary;
  }
}
