/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  TransferHelper,
  TransferHelperInterface,
} from "../../../../contracts/dex/libraries/TransferHelper";

const _abi = [
  {
    inputs: [],
    name: "TransferHelper__ApproveFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "TransferHelper__ETHTransferFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "TransferHelper__TransferFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "TransferHelper__TransferFromFailed",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea26469706673582212200f94e30bd6f5445be75a8464ce8a1bfd1e208a485a3ace44d0ca2111759f29b564736f6c63430008220033";

type TransferHelperConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TransferHelperConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TransferHelper__factory extends ContractFactory {
  constructor(...args: TransferHelperConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TransferHelper & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): TransferHelper__factory {
    return super.connect(runner) as TransferHelper__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TransferHelperInterface {
    return new Interface(_abi) as TransferHelperInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TransferHelper {
    return new Contract(address, _abi, runner) as unknown as TransferHelper;
  }
}
